site:
  title: Laboratoire de Julie
  url: http://vpn.jlab.ovh
  start_page: docs::index.adoc
content:
  sources:
  - url: https://github.com/Julie-b35/wiki-docs.git
  branches: HEAD
  edit_url: false
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true