site:
  title: Laboratoire de Julie
  url: http://vpn.jlab.ovh
  start_page: wiki::index.adoc
content:
  sources:
  - url: https://github.com/Julie-b35/wiki-docs.git
    branches: HEAD
    edit_url: false
    start_paths: 
    - wiki
    - cours
    - notes
    - procedures
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [main, v2.0, v1.0]
    start_path: docs
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: HEAD
    edit_url: false
runtime:
  fetch: true
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true