version: "3.9"
services:
  web:
    image: "httpd"
    ports:
      - "80:80"
    volumes:
      - ./conf:/usr/local/apache2/conf
      - ./build/site:/usr/local/apache2/htdocs
  antora:
    image: "antora/antora:latest"
    volumes:
      - .:/antora
