version: "3.9"
services:
  web:
    image: "httpd"
    ports:
      - "80:80"
    volumes:
      - ./conf:/usr/local/apache2/conf
      - ./public:/usr/local/apache2/htdocs
  antora:
    image: "antora/antora:latest"
    command: tail -f /dev/null
    environment:
      IS_TTY: false
    volumes:
      - .:/antora
